// const customer_records = <Map<String, Object>>[
//   {
//     "customer_name": "Sis Dambere",
//     "customer_details": {
//       "neck": 14,
//       "shoulder": 20,
//       "bust/chest": 37,
//       "sleeve": 16,
//       "waist": 30,
//       "hip/thigh": 30,
//       "full_length": 40,
//       "description": "Peplun top and skirt with ankara material",
//     },
//   },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Chukwu",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Cherish",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
//   // {
//   //   "customer_name": "Sis Aka",
//   //   "customer_details": {
//   //     "neck": 14,
//   //     "bust/chest": 37,
//   //     "waist": 30,
//   //     "hip": 30,
//   //     "half_length": 37,
//   //     "full_length": 40,
//   //     "shoulder": 20,
//   //     "sleeve": 16,
//   //     "description": "Peplun top and skirt with ankara material",
//   //   },
//   // },
// ];
